export const USER_ROLES = {
    ADMIN: 'ROLE_ADMIN',
    MERCHANT: 'ROLE_MERCHANT',
    MANUFACTURER: 'ROLE_MANUFACTURER'
}

export const OFFER_STATUS = {
    APPROVED: 'APPROVED',
    DECLINED: 'DECLINED',
    INITIAL: 'INITIAL',
}